# Generated by Django 5.1.7 on 2025-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('quantum_pattern_feature', models.FloatField()),
                ('prediction', models.IntegerField()),
            ],
        ),
    ]
